name: cresil
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.8.12
  - pip=22.0.4
  - biopython=1.79
  - minimap2=2.24
  - mappy=2.24
  - python-intervaltree=3.1.0
  - tqdm=4.63.0
  - pandas=1.4.1
  - jedi=0.18.1
  - ipykernel=6.9.1
  - pysam=0.18.0
  - pybedtools=0.9.0
  - openjdk=11.0.9.1
  - python-graphviz=0.19.1
  - matplotlib=3.5.1
  - networkx=2.7.1
  - samtools=1.15
  - bioawk=1.0
  - parallel=20220222
  - igvtools=2.5.3
  - bedtools=2.30.0
  - nanofilt=2.8.0
  - tabix=1.11
  - bcftools=1.15
  - medaka=1.5.0
  - mosdepth=0.3.3
  - circos=0.69.8
