name: cresil
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.8.15
  - pip=23.3.2
  - biopython=1.81
  - minimap2=2.26
  - mappy=2.26
  - python-intervaltree=3.1.0
  - tqdm=4.66.1
  - pandas=2.0.3
  - jedi=0.19.1
  - ipykernel=6.26.0
  - pysam=0.21.0
  - openjdk=17.0.3
  - python-graphviz=0.20.1
  - matplotlib=3.7.3
  - networkx=3.1
  - samtools=1.18
  - bioawk=1.0
  - parallel=20231122
  - igvtools=2.14.1
  - bedtools=2.31.1
  - pybedtools=0.9.1
  - nanofilt=2.8.0
  - tabix=1.11
  - bcftools=1.17
  - medaka=1.11.3
  - mosdepth=0.3.3
